[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Martin Ruefenacht", email = "martin.ruefenacht@lrz.de"},
]
dependencies = [
    "flask>=2.3.2",
    "bqp-database-access>=0.2",
    "pony>=0.7.16",
    "flask-jwt-extended>=4.5.2",
]
requires-python = ">=3.10,<3.11"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.0",
    "pytest-env>=0.8.2",
]

[tool.pytest.ini_options]
env = [
    "QUANTUM_DB_TESTING=TRUE",
    "QUANTUM_DB_FILENAME=test_db.sqlite",
    "QUANTUM_DB_USER=",
    "QUANTUM_DB_PASS=",
    "QUANTUM_DB_HOST="
]
